//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnicalServiceAndProductTracking
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillInformations
    {
        public int Id { get; set; }
        public string Serial { get; set; }
        public string SequenceNo { get; set; }
        public Nullable<System.DateTime> BillDate { get; set; }
        public string Time { get; set; }
        public string TaxAdministration { get; set; }
        public Nullable<int> Current { get; set; }
        public Nullable<int> Staff { get; set; }
    }
}
