//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnicalServiceAndProductTracking
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrentInformations
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string City { get; set; }
        public string District { get; set; }
        public string Bank { get; set; }
        public string TaxAdministration { get; set; }
        public string TaxNumber { get; set; }
        public string Status { get; set; }
    }
}
