//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnicalServiceAndProductTracking
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DboTechnicalServiceAndProductTrackingEntities : DbContext
    {
        public DboTechnicalServiceAndProductTrackingEntities()
            : base("name=DboTechnicalServiceAndProductTrackingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admins> Admins { get; set; }
        public virtual DbSet<BillDetails> BillDetails { get; set; }
        public virtual DbSet<BillInformations> BillInformations { get; set; }
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<CurrentInformations> CurrentInformations { get; set; }
        public virtual DbSet<Departments> Departments { get; set; }
        public virtual DbSet<Exponses> Exponses { get; set; }
        public virtual DbSet<FaultDetails> FaultDetails { get; set; }
        public virtual DbSet<MovementProduct> MovementProduct { get; set; }
        public virtual DbSet<Notes> Notes { get; set; }
        public virtual DbSet<ProductAcceptance> ProductAcceptance { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<ProductTracking> ProductTracking { get; set; }
        public virtual DbSet<Staffs> Staffs { get; set; }
        public virtual DbSet<Tools> Tools { get; set; }
    }
}
