//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnicalServiceAndProductTracking
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductTracking
    {
        public int Id { get; set; }
        public Nullable<int> Product { get; set; }
        public string Status { get; set; }
        public Nullable<int> TrackingDate { get; set; }
        public string TrackingCode { get; set; }
    }
}
