//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnicalService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DboTechnicalServiceAndProductTrackingEntities2 : DbContext
    {
        public DboTechnicalServiceAndProductTrackingEntities2()
            : base("name=DboTechnicalServiceAndProductTrackingEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBLAdmins> TBLAdmins { get; set; }
        public virtual DbSet<TBLBillDetails> TBLBillDetails { get; set; }
        public virtual DbSet<TBLBillInformations> TBLBillInformations { get; set; }
        public virtual DbSet<TBLCategories> TBLCategories { get; set; }
        public virtual DbSet<TBLCurrentInformations> TBLCurrentInformations { get; set; }
        public virtual DbSet<TBLDepartments> TBLDepartments { get; set; }
        public virtual DbSet<TBLExponses> TBLExponses { get; set; }
        public virtual DbSet<TBLFaultDetails> TBLFaultDetails { get; set; }
        public virtual DbSet<TBLMovementProduct> TBLMovementProduct { get; set; }
        public virtual DbSet<TBLNotes> TBLNotes { get; set; }
        public virtual DbSet<TBLProductAcceptance> TBLProductAcceptance { get; set; }
        public virtual DbSet<TBLProducts> TBLProducts { get; set; }
        public virtual DbSet<TBLProductTracking> TBLProductTracking { get; set; }
        public virtual DbSet<TBLStaffs> TBLStaffs { get; set; }
        public virtual DbSet<TBLTools> TBLTools { get; set; }
        public virtual DbSet<TBLAbout> TBLAbout { get; set; }
        public virtual DbSet<TBLMessage> TBLMessage { get; set; }
        public virtual DbSet<ilceler> ilceler { get; set; }
        public virtual DbSet<iller> iller { get; set; }
    
        public virtual ObjectResult<UrunKategori_Result> UrunKategori()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UrunKategori_Result>("UrunKategori");
        }
    
        public virtual ObjectResult<string> MaksKategoriUrun()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("MaksKategoriUrun");
        }
    
        public virtual ObjectResult<string> MaksUrunMarka()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("MaksUrunMarka");
        }
    }
}
