//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnicalService
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLProductAcceptance
    {
        public int Id { get; set; }
        public Nullable<int> Current { get; set; }
        public Nullable<int> Staff { get; set; }
        public Nullable<System.DateTime> ArrivalDate { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public string ProductSerialNo { get; set; }
        public Nullable<bool> Status { get; set; }
        public string StatusDetail { get; set; }
    }
}
